name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install cabal/ghc
      uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: '9.8.2'
        cabal-version: '3.10.3.0'
    
    - name: Generate freeze file
      run: |
        cabal update
        cabal configure --disable-optimization
        cabal freeze
    
    - name: Cache cabal work
      uses: actions/cache@v4
      with:
        path: |
          dist-newstyle
          ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ hashFiles('cabal.project.freeze', 'cabal.project.local') }}-cabal-install
    
    - name: Build all dependencies
      run: |
        cabal build --enable-tests --only-dependencies
    
    - name: Build all
      run: |
        cabal build --enable-tests
        
    - name: Run tests
      run: |
        cabal test